ej/urls.py
from django.conf.urls import patterns, url
from ej import views

urlpatterns = patterns('',
        url(r'^$', views.home, name = 'home'),
        url(r'^about/', views.about, name = 'about'),
        url(r'^skills/', views.skills, name = 'skills'),
        url(r'^courses/', views.courses, name = 'courses'),
        url(r'^jobs/', views.jobs, name = 'jobs'),
        url(r'^job_search/', views.job_search, name = 'job_search'),
        url(r'^job_detail/(?P<job_id>\d+)/$', views.job_detail, name = 'job_detail'),
        url(r'^course_search/', views.course_search, name = 'course_search'),
        url(r'^course_detail/(?P<course_id>\d+)/$', views.course_detail, name = 'course_detail'),
        url(r'^from_skill_find_courses/', views.from_skill_find_courses),
        url(r'^quick_ref_course_detail/', views.quick_ref_course_detail),
        url(r'^get_jobs/', views.get_jobs),
        url(r'^filter_jobs/', views.filter_jobs),
        url(r'^from_job_get_skill', views.from_job_get_skill),
        url(r'^get_other_skills_needed', views.get_other_skills_needed)
        )

ejub/urls.py
import settings
from django.conf.urls import patterns, include, url
from django.views.generic import RedirectView
from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'ejub.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),
    url(r'^$', RedirectView.as_view(url='/ej/')),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^ej/', include('ej.urls', namespace = 'ej')),
    url(r'^accounts/', include('allauth.urls')),
)

ej/models.py
# This is an auto-generated Django model module.
# You'll have to do the following manually to clean this up:
#   * Rearrange models' order
#   * Make sure each model has one field with primary_key=True
#   * Remove `managed = False` lines for those models you wish to give write DB access
# Feel free to rename the models, but don't rename db_table values or field names.
#
# Also note: You'll have to insert the output of 'django-admin.py sqlcustom [appname]'
# into your database.
from __future__ import unicode_literals

from django.db import models

class SkillsList(models.Model):
    id = models.IntegerField(db_column='ID', primary_key=True) 
    skill = models.CharField(max_length=255)

    def __unicode__(self):
        return self.skill

    class Meta:
        managed = True
        db_table = 'skills_list'

class CoursesList(models.Model):
    id = models.IntegerField(db_column='ID', primary_key=True)  
    coursedescription = models.TextField(db_column='courseDescription', blank=True) 
    courseuid = models.CharField(db_column='courseUID', max_length=30, blank=True) 
    coursetitle = models.CharField(db_column='courseTitle', max_length=255, blank=True) 
    upperunits = models.IntegerField(db_column='upperUnits', blank=True, null=True) 
    uri = models.URLField(blank=True)
    lowerunits = models.IntegerField(db_column='lowerUnits', blank=True, null=True) 
    departmentcode = models.CharField(db_column='departmentCode', max_length=30, blank=True) 
    coursenumber = models.CharField(db_column='courseNumber', max_length=30, blank=True) 
    subdepartmentcode = models.CharField(db_column='subDepartmentCode', max_length=30, blank=True) 

    skillsLists = models.ManyToManyField(SkillsList)

    def __unicode__(self):
        return self.coursetitle

    class Meta:
        managed = True
        db_table = 'courses_list'

class JobsList(models.Model):
    id = models.IntegerField(db_column='ID', primary_key=True) 
    job_id = models.IntegerField()
    city = models.CharField(db_column='City', max_length=50, blank=True) 
    region = models.CharField(db_column='Region', max_length=50, blank=True) 
    country = models.CharField(db_column='Country', max_length=50, blank=True) 
    company = models.CharField(db_column='Company', max_length=100, blank=True) 
    description = models.TextField(db_column='Description', blank=True) 
    title = models.CharField(db_column='Title', max_length=100, blank=True) 
    experience = models.CharField(db_column='Experience', max_length=100, blank=True) 
    skills = models.TextField(db_column='Skills', blank=True) 
    posted = models.DateTimeField(db_column='Posted', blank=True, null=True) 
    employmenttype = models.CharField(db_column='EmploymentType', max_length=50, blank=True) 
    functions = models.CharField(db_column='Functions', max_length=100, blank=True) 
    industry = models.CharField(db_column='Industry', max_length=150, blank=True) 

    skillsLists = models.ManyToManyField(SkillsList)

    def __unicode__(self):
        return self.title

    class Meta:
        managed = True
        db_table = 'jobs_list'

ej/views.py
import MySQLdb
import collections
import json
from django.utils import timezone
import datetime
from ej.models import CoursesList, SkillsList, JobsList
from django.db.models import Sum, Count
from django.shortcuts import render, render_to_response
from django.http import HttpResponseRedirect, HttpResponse
from django.template import RequestContext
from django.core.urlresolvers import reverse

def home(request):
    context = RequestContext(request)
    return render_to_response('ej/home.html', context)

def about(request):
    context = RequestContext(request)
    return render_to_response('ej/about.html', context)
def courses(request):
    context = RequestContext(request)
    return render_to_response('ej/courses.html', context)

def skills(request):
    pass

def jobs(request):
    context = RequestContext(request)
    return render_to_response('ej/jobs.html', context)


def search_job(max_jobs = 0, starts_with = {}):
    job_list = []
    if starts_with:
        filterargs = {}
        # Create the filter that has all the input fields as searches
        for k,v in starts_with.iteritems():
            if v:
                # Ignore case
                filterargs['{0}__{1}'.format(k, 'icontains')] = v
        
        if filterargs:
            job_list = JobsList.objects.filter(**filterargs)
        else:
            job_list = JobsList.objects.all()
    else:
        job_list = JobsList.objects.all()

    if max_jobs > 0:
        if len(job_list) > max_jobs:
            job_list = job_list[:max_jobs]

    return job_list

def job_search(request):
    context = RequestContext(request)
    starts_with = ''
    job_list = []
    
    field_list = ['title', 'company', 'country', 'city']
    starts_with = {}

    if request.method == "GET":
        for field in field_list:
            starts_with[field] = request.GET['search_' + field]
    else:
        for field in field_list:
            starts_with[field] = request.POST['search_' + field]

    job_list = search_job(15, starts_with)
    return render_to_response('ej/job_search.html', {'job_list': job_list}, context)


def search_course(max_courses = 0, starts_with = {}):
    course_list = []
    if starts_with:
        filterargs = {}
        # Create the filter that has all the input fields as searches
        for k,v in starts_with.iteritems():
            if v:
                # Ignore case
                filterargs['{0}__{1}'.format(k, 'icontains')] = v
        
        if filterargs:
            course_list = CoursesList.objects.filter(**filterargs)
        else:
            course_list = CoursesList.objects.all()
    else:
        course_list = CoursesList.objects.all()

    if max_courses > 0:
        if len(course_list) > max_courses:
            course_list = course_list[:max_courses]

    return course_list

def course_search(request):
    context = RequestContext(request)
    starts_with = ''
    course_list = []
    
    field_list = ['coursetitle', 'departmentcode', 'courseuid']
    starts_with = {}

    if request.method == "GET":
        for field in field_list:
            starts_with[field] = request.GET['search_' + field]
    else:
        for field in field_list:
            starts_with[field] = request.POST['search_' + field]

    course_list = search_course(15, starts_with)
    return render_to_response('ej/course_search.html', {'course_list': course_list}, context)

# Once the user finds the course, retrieve the course detail
def course_detail(request, course_id):
    context = RequestContext(request)
    course = {}
    related_jobs = []
    related_jobs_id = []
    # The maximum amount of related jobs that can be shown
    max_jobs = 15
    if course_id:
        course = CoursesList.objects.get(pk = course_id)
        related_jobs = sort_by_relevance(course.skillsLists.all(), max_jobs)

    return render_to_response('ej/course_detail.html', {'course': course, 'related_jobs': related_jobs}, context) 

# Once the user finds the course, retrieve the course detail
def job_detail(request, job_id):
    context = RequestContext(request)
    job = {}
    related_courses = []
    # The maximum amount of related jobs that can be shown
    max_courses = 15
    if job_id:
        job = JobsList.objects.get(pk = job_id)
        for skill in job.skillsLists.all():
            if len(related_courses) <= max_courses:
                related_courses += skill.courseslist_set.all()
            else:
                break
        if len(related_courses) > max_courses:
            related_courses = related_courses[:max_courses]

        job.description = job.description.replace("|"," ")
        job.skills = job.skills.replace("|", " ")
    return render_to_response('ej/job_detail.html', {'job': job, 'related_courses': related_courses}, context) 

def from_skill_find_courses(request):
    context = RequestContext(request)
    courses = []
    max_courses = 15
    skill = {}
    if request.method == "GET":
        skill_id = request.GET['skill_id']
        if skill_id:
            skill = SkillsList.objects.get(pk = skill_id)
            courses += skill.courseslist_set.all()
            if len(courses) > max_courses:
                courses = courses[:max_courses]
    else:
        skill_id = request.POST['skill_id']

    return render_to_response('ej/from_skill_find_courses.html', {'courses': courses, 'skill': skill}, context)

def quick_ref_course_detail(request):
    context = RequestContext(request)
    course_id = 0
    if request.method == "GET":
        course_id = request.GET['course_id'] 

    return render_to_response('ej/quick_ref_course_detail.html', {'course_id': course_id}, context)

def get_jobs(request):
    context = RequestContext(request)
    # The maximum amount of categories that can be shown in the quick navigation bar
    max_counts = 6
    top_counts = []
    course_id = 0
    field = None
    if request.method == "GET":
        field = request.GET['field']
        course_id = request.GET['course_id']
        the_field_set = request.GET.getlist("the_field_set[]")
        sub_field_set = request.GET.getlist("sub_field_set[]")
        other_fields_set = request.GET.getlist("other_fields_set[]")
        if field and course_id:
            related_jobs_id = []
            for skill in CoursesList.objects.get(pk = course_id).skillsLists.all():
                # Get all the ids for the related job, now create a sql table to facilitate query group by
                if the_field_set and sub_field_set and len(the_field_set) == len(sub_field_set):
                    kwargs = {}
                    exclude_kwargs = {}
                    for i in range(len(the_field_set)):
                        if sub_field_set[i] != "Other":
                            kwargs['{0}__{1}'.format(the_field_set[i], 'exact')] = sub_field_set[i]
                        else:
                            other_fields_tmp = [str(k.strip().replace('"','')) for k in other_fields_set[i].strip('[]').split(',')]
                            exclude_kwargs['{0}__{1}'.format(the_field_set[i], 'in')] = other_fields_tmp
                    related_jobs_id += [i.id for i in skill.jobslist_set.filter(**kwargs).exclude(**exclude_kwargs)]
                else:
                    related_jobs_id += [ i.id for i in skill.jobslist_set.all()]

            if field == "all":
                pass
            # Need special treatment for date type, rank by recent to old
            elif field == "posted":
                jobs_tmp = JobsList.objects.filter(id__in = related_jobs_id)
                # Use tuple in order to keep the order
                times_count = (('Past week', 0), ('Past month', 0), ('Past quarter', 0), ('Past year', 0), ('Past 3 years', 0), ('3 years older', 0))
                times_count = collections.OrderedDict(times_count)
                for j in jobs_tmp:
                    time_passed = None
                    # Convert to number of days that has passed
                    time_passed =  ((timezone.now() - j.posted).days)
                    if time_passed or time_passed == 0:
                        # Past week
                        if time_passed <= 7:
                            times_count['Past week'] += 1
                        # Past month
                        elif time_passed <= (365 / 12):
                            times_count['Past month'] += 1
                        # Past quarter
                        elif time_passed <= (3 * 365 / 12):
                            times_count['Past quarter'] += 1
                        # Past year
                        elif time_passed <= 365.25:
                            times_count['Past year'] += 1
                        # Past three years
                        elif time_passed <= 3 * 365.25:
                            times_count['Past 3 years'] += 1
                        # More than three years from now
                        else:
                            times_count['3 years older'] += 1
                    
                top_counts = [{'count':v, 'field': k} for k,v in times_count.iteritems()]

            else:
                top_counts = JobsList.objects.filter(id__in = related_jobs_id)\
                        .values(field) \
                        .annotate(count = Count('id')) \
                        .order_by('-count')
                
                # If more than max_counts category, group the extra into "others"
                if len(top_counts) > max_counts:
                    other_counts = top_counts[(max_counts-1):]
                    count_other = 0
                    for each in other_counts:
                        count_other += each['count']
                    top_counts = top_counts[:(max_counts-1)]
                    # Add the name of other fields in case user click on 'Other'
                    other_fields = [f[field] for f in top_counts]

ej/templates/ej/about.html
{% extends 'ej/base.html' %}
{% block title %}
About Ejub 
{% endblock %}
{% block body %}

<div class="container-fluid">
    <div class="row-fluid">
        <div class="span10">

            <p>
            Which class to take to prepare myself for..? How do I become an analyst at..? Questions like those were not uncommon among college students. On the other hand, the gap between the industry demand and what the school teaches has never been wider. Ejub summarizes the required skills from job postings and links to the courses that teach those skills. Ejub completes these sentences:
            </p>
            <p>
            <ul>
                <li>
                By taking this course I could learn …, which prepares me for … at company …, and I will also be ready for this industry … 
                </li>
                <li>
                In order to become a … at company … (or a graduate student at …), the required skills are …, and here are my planned courses over the next two years: …
                </li>
            </ul>
            <br />
            <p>
            Ejub, from education to job. This site is the prototype to demonstrate the idea. The prototype operates on a sample job database which only contains around 2,000 jobs at the moment. It starts with the courses at UC Berkeley which will be our first test-ground. 
            </p>
            <p>
            About me: I am a graduate of Haas School of Business with a master’s in financial engineering. Have a full-time job in San Francisco but I spend my spare time in this project. 
            If you have any suggestions or if you are interested in doing this project together, please feel free to contact me at <a href="mailto:kevinyang@ejub.us">kevinyang@ejub.us</a>
            There is a LOT of things to improve and the project will get very data-intensive. Highly preferred if you have skills in Python, NLP, databases, machine-learning, and/or web programming (we use Django at this moment). 
            </p>
            <br/>
            <a class="btn btn-primary" href="{% url 'ej:home' %}">Home page</a>

        </div>

        <div class="span2">
            <div id="quick-ref" class="well sidebar-nav">
                <ul class="nav nav-list">
                    <li class="nav-header">Get started</li>
                    <a href="{% url 'ej:courses' %}">Search courses</a>
                    <br />
                    <a href="{% url 'ej:jobs' %}">Search jobs</a>
                </ul>
            </div>
        </div>
    </div>
</div>
{% endblock %}

ej/templates/ej/home_bk.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
    <head>
        <meta name="viewpoint" content="width=device-with, initial-scale=1.0">
        <link href="{% static 'css/bootstrap-fluid-adj.css' %}" rel="stylesheet">
        <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet" media="screen">
        <link href="{% static 'css/bootstrap-responsive.css' %}" rel="stylesheet">
        <link href="{% static 'css/ej.css' %}" rel="stylesheet">
        <script type="text/javascript" src="{% static 'js/jquery-2.0.3.min.js' %}"></script>
        <title>Ejub! - {% block title%}Edu to Job!{% endblock %}</title>
        <style type="text/css">
            footer {
                margin-top: 30px;
            }
            #section-img-first {
                background: url("{% static 'img/ucberkeley.jpg' %}") 50% 0 no-repeat fixed; 
                background-size: 1500px 800px;
                min-height: 750px;
                height: 750px;
                margin: -100px 0 0 0;
                width: 100%;
                max-width: 1920px;
                position: relative;
            }

            #section-img-first h2 {
                height: 458px;
                position: absolute;
                text-align: center;
                top: 40%;
                width: 100%;
            }

            #section-img-second {
                background: url("{% static 'img/ucberkeley2.jpg' %}") 50% 0 no-repeat fixed;
                background-size: 1500px 1125px;
                min-height: 900px;
                height: 900px;
                margin: 0 0 0 0;
                width: 100%;
                max-width: 1920px;
                position: relative;
            }

            #section-img-second h2 {
                height: 458px;
                position: absolute;
                text-align: center;
                top: 40%;
                width: 50%;
                left: 25%;
            }

            #section-img-third {
                background: url("{% static 'img/ucberkeley3.jpg' %}") 0 0 / 0 0 no-repeat fixed;
                background-size: 1500px 1400px;
                min-height: 700px;
                height: 700px;
                margin: 0 0 0 0;
                width: 100%;
                max-width: 1920px;
                position: relative;
            }

            #section-img-third h2 {
                height: 458px;
                position: absolute;
                text-align: center;
                top: 40%;
                width: 70%;
                left: 15%;
            }


            #section-txt-first {
                background-color:#F5F5F5;
                height: 300px;
                margin: -10px 0 0 0;
                width: 100%;
                max-width: 1920px;
                position: relative;
                -webkie-box-shadow: 0 0 50px rgba(0,0,0,0.8);
                box-shadow: 0 0 50px rgba(0,0,0,0.8);
            }

            #section-txt-first h2 {
                position: relative;
                text-align: center;
                top: 60px;
                width: 100%;
            }

            #section-txt-first p {
                position: relative;
                font-size: 20px;
                text-align: center;
                top: 100px;
                width: 60%;
                left: 20%;
            }

            #section-txt-second {
                background-color:#F5F5F5;
                height: 300px;
                margin: -10px 0 0 0;
                width: 100%;
                max-width: 1920px;
                position: relative;
                -webkie-box-shadow: 0 0 50px rgba(0,0,0,0.8);
                box-shadow: 0 0 50px rgba(0,0,0,0.8);
            }

            #section-txt-second h2 {
                position: relative;
                text-align: center;
                top: 60px;
                width: 100%;
            }

            #section-txt-second p {
                position: relative;
                font-size: 20px;
                text-align: center;
                top: 100px;
                width: 58%;
                left: 21%;
            }

            #section-txt-third {
                background-color:#F5F5F5;
                height: 400px;
                margin: -10px 0 0 0;
                width: 100%;
                max-width: 1920px;
                position: relative;
                -webkie-box-shadow: 0 0 50px rgba(0,0,0,0.8);
                box-shadow: 0 0 50px rgba(0,0,0,0.8);
            }

            #section-txt-third h2 {
                position: relative;
                text-align: center;
                top: 60px;
                width: 100%;
            }

            #section-txt-third p {
                position: relative;
                font-size: 20px;
                text-align: center;
                top: 100px;
                width: 58%;
                left: 21%;
            }

            #section-txt-third div {
                position: relative;
                text-align: center;
                top: 120px;
                width: 30%;
                left: 35%;
            }

        </style>
    </head>
    <body>
        <div class="navbar navbar-inverse navbar-fixed-top">
            <div class="navbar-inner">
                <div class="container">
                    <button type="button" class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <a class="brand" href="{% url 'ej:home' %}"><strong>Ejub</strong></a>

                    <div class="nav-collapse collapse">
                        <ul class="nav">
                            <li><a href="{% url 'ej:courses' %}">Courses</a></li>
                            <li><a href="{% url 'ej:skills' %}">Skills</a></li>
                            <li><a href="{% url 'ej:jobs' %}">Jobs</a></li>
                        </ul>
                        <ul class="nav pull-right">
                            <li><a href="{% url 'ej:about' %}">About</a></li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>

            <section id="section-img-first" data-type="background" data-speed="10">
            <h2 style="color: white;">Ejub. From education to job.</h2>
            </section>
            <section id="section-txt-first" data-type="background" data-speed="10">
            <h2>What is Ejub?</h2>
            <p>From education to job. We try to dig into the link between the courses taught in school and the jobs to be filled in the industry using quantitave methods. </p>
            </section>
            <section id="section-img-second" data-type="background" data-speed="10">
            <h2 style="color: white;">Bridge the gap between what education provides and what industry demands</h2>
            </section>

            <section id="section-txt-second" data-type="background" data-speed="10">
            <h2>How does it work?</h2>
            <p><a href="{% url 'ej:courses' %}">Search for a class</a> before you enroll. Ejub tells you what skills are taught in the class and what jobs are related to the skills.</p> 
            <p><a href="{% url 'ej:jobs' %}">Search for your ideal job</a> to see what class you should take to prepare for it.</p>
            </section>

<section id="section-img-third" data-type="background" data-speed="10">
<h2>Prepare students early for their future.</h2>
            </section>
 
            <section id="section-txt-third" data-type="background" data-speed="10">
            <h2>More to expect. Soon.</h2>
            <p>We could plot the most demanded skills over time to see if there's any interesting patterns. We could add suggestions for internships in addition to full-time jobs. We could also get feedbacks from graduates on their experience of education to jobs...There is a UNIVERSE of interesting things we could do.</p>
            <br />
            <p>Get started now by:</p>
            <div>
                <a class="btn btn-primary" style="display:inline; float:left" href="{% url 'ej:courses' %}">Search courses</a>
                <a class="btn btn-primary" style="display:inline; float:right" href="{% url 'ej:jobs' %}">Search jobs</a>
            </div> 
            </section>

   
        <footer>
        <div class="container">
            <p>&copy; Ejub: from education to jobs.</p>
        </div>
        </footer>
        <script type="text/javascript" src="{% static 'js/bootstrap.min.js' %}"></script>
        <script type="text/javascript" src="{% static 'js/ej-ajax.js' %}"></script>
        <script type="text/javascript">
            $(document).ready(function() {
                    $('section[data-type="background"]').each(function() {
                        var $bgobj = $(this);
                        $(window).scroll(function() {
                            var yPos = -($(this).scrollTop() / $bgobj.data('speed'));
                            // Put together our final background position
                            var coords = '50% ' + yPos + 'px';

                            //Move the background
                            $bgobj.css({backgroundPosition: coords});
                            });
                        });
                    });
                </script>
            </body>
        </html>

ej/templates/ej/job_detail.html
{% extends 'ej/base.html' %}
{% block body %}

<div class="container-fluid">
    <div class="row-fluid">
        <div class="span10">

            <div class="container-fluid">
                {% if job %}
                <h2>{{ job.title }}</h2>
                <div class="row-fluid">
                    <div class="span4">
                        <h4>Job information</h4>
                        <ul>
                            <li>Company: {{ job.company }}</li>
                            <li>Industry: {{ job.industry }}</li>
                            <li>Functions: {{ job.functions }}</li>
                            {% if job.city %}
                            <li>Location: {{ job.city }}, {{ job.country }}</li>
                            {% else %}
                            <li>Location: {{ job.country }}</li>
                            {% endif %}
                            <li>Experience: {{ job.experience }}</li>
                            <li>Posted: {{ job.posted }}</li>
                            <li>Description: {{ job.description }}</li>
                            <li>Requirements: {{ job.skills }}</li>
                        </ul>
                    </div>

                    <div class="span4">
                        <h4 class="job-required-skills">Skills</h4>
                        <ul>
                            {% for skill in job.skillsLists.all %}
                            <li skill_id={{ skill.id }} class="job-required-skills">{{ skill.skill }}</li>
                            {% endfor %}
                        </ul>
                    </div>

                    <div id="job-related-courses" class="span4">
                        <h4 id="job-related-courses-header">All related courses</h4>
                        {% if related_courses %}
                        <ul>
                            {% for course in related_courses %}
                            <li><a href="{% url 'ej:course_detail' course.id %}">{{ course.coursetitle }}</a></li>
                            {% endfor %}
                        </ul>
                        {% endif %}
                    </div>
                </div>
                {% else %}
                <strong>Error retrieving the job.</strong>
                {% endif %}
            </div>

        </div>

        <div class="span2">
            <div id="quick-ref" class="well sidebar-nav">
                <ul class="nav nav-list">
                    <li class="nav-header">Get started</li>
                    <a href="{% url 'ej:courses' %}">Search courses</a>
                    <br />
                    <a href="{% url 'ej:jobs' %}">Search jobs</a>
                </ul>
            </div>
        </div>
    </div>
</div>
{% endblock %}

ej/templates/ej/jobs.html
{% extends 'ej/base.html' %}
{% load static %}
{% block title %}Browse by jobs{% endblock %}
{% block body %}

<div class="container-fluid">
    <div class="row-fluid">
        <div class="span10">

            <div class="container-fluid">
                <h1 id="course-page-head">Search for a job</h1>
                <div class="row-fluid">
                    <div class="span6">
                        <br/>
                        <form class="form-signin span8" method="post" id="course_search_form" action="{% url 'ej:courses' %}">
                            {% csrf_token %}
                            <input type="text" class="input-long search-query" size="50" name="query-job-title" id="query-job-title" placeholder="Job Title"/>
                            <br/>
                            <br/>
                            <input type="text" class="input-long search-query" size="50" name="query-job-company" id="query-job-company" placeholder="Company"/>
                            <br/>
                            <br/>
                            <input type="text" class="input-long search-query" size="50" name="query-job-country" id="query-job-country" placeholder="Country"/>
                            <br/>
                            <br/>
                            <input type="text" class="input-long search-query" size="50" name="query-job-city" id="query-job-city" placeholder="City"/>

                        </form>
                    </div>

                    <div class="span6">
                        <div id="job-suggestions">Suggested jobs.</div>
                    </div>
                </div>
            </div>
        </div>

        <div class="span2">
            <div id="quick-ref" class="well sidebar-nav">
                <ul class="nav nav-list">
                    <li class="nav-header">Get started</li>
                    <a href="{% url 'ej:courses' %}">Search courses</a>
                    <br />
                    <a href="{% url 'ej:jobs' %}">Search jobs</a>
                </ul>
            </div>
        </div>
    </div>
</div>
{% endblock %}